steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - hello_world
      - --gen2
      - --runtime=python314
      - --region=asia-northeast1
      - --source=.
      - --entry-point=hello_world
      - --trigger-http
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
